<?php
declare(strict_types=1);
require dirname(__DIR__).'/src/bootstrap.php'; require dirname(__DIR__).'/src/auth.php';
use Firebase\JWT\JWT;
$m=$_SERVER['REQUEST_METHOD']; $path=trim(parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH),'/');
try {
 if($m==='POST'&&$path==='api/v1/auth/register'){ $i=input(); foreach(['fullName','email','phoneNumber','password'] as $f) if(empty($i[$f])) fail("Missing $f"); if(!filter_var($i['email'],FILTER_VALIDATE_EMAIL)||strlen($i['password'])<10) fail('Invalid registration data'); $id=uuid(); $s=db()->prepare('INSERT INTO users(id,full_name,email,phone,password_hash) VALUES(?,?,?,?,?)'); $s->execute([$id,$i['fullName'],strtolower($i['email']),$i['phoneNumber'],password_hash($i['password'],PASSWORD_DEFAULT)]); foreach(['USD','EUR'] as $c) db()->prepare('INSERT INTO wallets(id,user_id,currency) VALUES(?,?,?)')->execute([uuid(),$id,$c]); respond(['token'=>token(['id'=>$id,'email'=>$i['email']]),'userId'=>$id],201); }
 if($m==='POST'&&$path==='api/v1/auth/login'){ $i=input(); $s=db()->prepare('SELECT * FROM users WHERE email=?'); $s->execute([strtolower((string)($i['email']??''))]); $u=$s->fetch(); if(!$u||!password_verify((string)($i['password']??''),$u['password_hash'])) fail('Invalid credentials',401); respond(['token'=>token($u),'userId'=>$u['id']]); }
 $uid=userId();
 if($m==='GET'&&$path==='api/v1/wallets'){ $s=db()->prepare('SELECT id,currency,balance,status FROM wallets WHERE user_id=? ORDER BY currency'); $s->execute([$uid]); respond(['wallets'=>$s->fetchAll()]); }
 if($m==='GET'&&$path==='api/v1/transactions'){ $s=db()->prepare('SELECT * FROM transactions WHERE user_id=? ORDER BY created_at DESC LIMIT 100'); $s->execute([$uid]); respond(['transactions'=>$s->fetchAll()]); }
 if($m==='POST'&&$path==='api/v1/transfers'){ $i=input(); $a=(float)($i['amount']??0); $c=strtoupper((string)($i['currency']??'')); $r=(string)($i['recipient']??''); $key=$_SERVER['HTTP_IDEMPOTENCY_KEY']??''; if($a<=0||!$c||!$r||!$key) fail('amount, currency, recipient and Idempotency-Key are required'); $p=db(); $p->beginTransaction(); $q=$p->prepare('SELECT response_code,response_body FROM idempotency_keys WHERE user_id=? AND idempotency_key=? FOR UPDATE'); $q->execute([$uid,$key]); if($x=$q->fetch()){ $p->commit(); respond(json_decode($x['response_body'],true),(int)$x['response_code']); } $q=$p->prepare('SELECT id,balance FROM wallets WHERE user_id=? AND currency=? AND status="active" FOR UPDATE'); $q->execute([$uid,$c]); $w=$q->fetch(); if(!$w||(float)$w['balance']<$a){$p->rollBack();fail('Insufficient balance',422);} $id=uuid(); $p->prepare('UPDATE wallets SET balance=balance-? WHERE id=?')->execute([$a,$w['id']]); $p->prepare('INSERT INTO transactions(id,user_id,type,provider,amount,currency,counterparty,status,idempotency_key) VALUES(?,?,?,?,?,?,?,?,?)')->execute([$id,$uid,'send','internal',$a,$c,$r,'completed',$key]); $body=['transactionId'=>$id,'status'=>'completed']; $p->prepare('INSERT INTO idempotency_keys(user_id,idempotency_key,response_code,response_body) VALUES(?,?,?,?)')->execute([$uid,$key,201,json_encode($body)]); $p->commit(); respond($body,201); }
 fail('Not found',404);
} catch(PDOException $e){ error_log($e->getMessage()); fail('Database operation failed',500); } catch(Throwable $e){ error_log($e->getMessage()); fail('Request failed',500); }
